-- Usamos pgcrypto para generar UUIDs
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Creación de la tabla de Franquicias (Franchises)
CREATE TABLE franchises
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid       UUID NOT NULL DEFAULT gen_random_uuid(),
    name       VARCHAR(150) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    is_active  BOOLEAN NOT NULL DEFAULT TRUE
);

ALTER TABLE franchises ADD CONSTRAINT pk_franchises PRIMARY KEY (id);
ALTER TABLE franchises ADD CONSTRAINT uc_franchises_uuid UNIQUE (uuid);

-- Índices para búsquedas comunes
CREATE INDEX idx_franchises_name ON franchises (name);
