-- Creación de la tabla de Sucursales (Branches)
CREATE TABLE branches
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid       UUID NOT NULL DEFAULT gen_random_uuid(),
    name       VARCHAR(150) NOT NULL,
    franchise_id BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    is_active  BOOLEAN NOT NULL DEFAULT TRUE
);

ALTER TABLE branches ADD CONSTRAINT pk_branches PRIMARY KEY (id);
ALTER TABLE branches ADD CONSTRAINT uc_branches_uuid UNIQUE (uuid);
ALTER TABLE branches ADD CONSTRAINT fk_branches_on_franchise FOREIGN KEY (franchise_id) REFERENCES franchises (id);

-- Índices para búsquedas comunes
CREATE INDEX idx_branches_name ON branches (name);
