-- Creación de la tabla de Productos (products)
CREATE TABLE products
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid       UUID NOT NULL DEFAULT gen_random_uuid(),
    name       VARCHAR(150) NOT NULL,
    stock      INTEGER NOT NULL DEFAULT 0,
    branch_id BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    is_active  BOOLEAN NOT NULL DEFAULT TRUE
);

ALTER TABLE products ADD CONSTRAINT pk_products PRIMARY KEY (id);
ALTER TABLE products ADD CONSTRAINT uc_products_uuid UNIQUE (uuid);
ALTER TABLE products ADD CONSTRAINT fk_products_on_branch FOREIGN KEY (branch_id) REFERENCES branches (id);

-- Índices para búsquedas comunes
CREATE INDEX idx_products_name ON products (name);

-- Creación de índices para optimizar búsquedas
CREATE INDEX idx_branches_franchise_id ON branches (franchise_id);
CREATE INDEX idx_products_branch_id ON products (branch_id);